collections:
  projects:
    output: true

# Paginate
paginate: 1
paginate_path: "/pagination/page:num/"


# Plugins
plugins:
  - jekyll-multiple-languages-plugin
  - jekyll-paginate


# jekyll-multiple-languages-plugin settings:
languages: ["en", "de"]

exclude_from_localizations: ["javascript", "images", "css", "scripts", "favicon.ico"]